Remove PYTHONPATH variable
It seems that arm* architecture does not like thi PYTHONPATH location:
TEST FAILED: build/bdist.linux-armv7l/wheel/ does NOT support .pth files
  error: bad install directory or PYTHONPATH